/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.cst8288Lab2;

import org.junit.Test;


class AppTest {
	
    @Test 
    void appHasAGreeting() {
        App classUnderTest = new App();
        //assertNotNull(classUnderTest.main(), "app should have a greeting");
    }
}
